Cleaner errors and optionally enable skipping wrong packages
alex-nitrokey/python-pgpdump pull request #4
Opened 2020-10-12 11:38 UTC by htgoebel

This brings in https://github.com/dkg/python-pgpdump/tree/cleaner-errors pluss some minor changes by me.

2020-10-12 11:41 UTC, htgoebel commented
Please note: This pull-request also includs some changes already in #3 due to how dkg did apply the changes in his repo. Anyway, please merge #2 first to have that branch merge into here. Thus others can easily see that dpk'g changes are in here already. Thanks.

2020-10-12 15:46 UTC, alex-nitrokey commented
Thank you very much for your effort creating this PR! I will look into this one during the week.

2020-10-14 15:00 UTC, alex-nitrokey requested changes
Thanks again for this PR. Would you mind creating a test case in test.py that checks and demonstrates the new feature of packet skipping and encoding? That'd be awesome. I guess, I would merge this PR anyway, but I would really prefer having this tested in future to prevent breaking stuff unintentionally.

2020-10-14 15:00 UTC, alex-nitrokey commented on pgpdump/utils.py
> +def encode_packet(tag, new, data, armored=False):
It would be great to have a function description here.

2021-12-08 10:50 UTC, htgoebel commented
@alex-nitrokey Sorry for the delay, I was completely distracted from this issue. Now I updates the pull-request and added what you requested.

2021-12-08 14:54 UTC, htgoebel commented
Lint errors are from code untouched by me.

2021-12-09 08:46 UTC, alex-nitrokey commented
> Sorry for the delay, I was completely distracted from this issue. Now I updates the pull-request and added what you requested.

No harm done, thanks for your contribution and efforts!

> Lint errors are from code untouched by me.

Some are ;) I think I fixed them, but couldn't apply them directly to you PR, so I created a [new branch](https://github.com/alex-nitrokey/python-pgpdump/tree/lint-fixes)... See [this commit](https://github.com/alex-nitrokey/python-pgpdump/commit/b3b858a9fde21d2443e02401e51cbadec9b4572c). If you check the correct box in the PR settings I might be able to include it right away here. Or please see if you can just merge the commit. Or I will just merge your PR and fix the minor lint errors afterwards.

Anyway I thank you for contributing to this software I am not even using anymore...

2021-12-16 15:57 UTC, merged

2021-12-16 15:57 UTC, alex-nitrokey commented
Again, thanks a lot!